apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rediscartsvc.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.rediscartsvc.selector.app }}
  ports:
  - name: redis
    port: {{ .Values.rediscartsvc.ports.redis }}
    targetPort: {{ .Values.rediscartsvc.targetPorts.redis }}